import express from 'express';
import cors from 'cors';
import { createSession, getSession, deleteSession, cleanupStaleSessions } from './sessions.js';
import { spawnClaude, killAllClaudeProcesses } from './claude-bridge.js';
import { streamCodex } from './codex-bridge.js';
import { writeGeneratedFile, tryOpenEditor, cleanupGeneratedFiles } from './trae-bridge.js';

const app = express();
const PORT = 4001;

app.use(cors({
  origin: ['http://localhost:5173', 'http://localhost:3000', 'http://localhost:3002'],
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
}));

app.use(express.json());

setInterval(cleanupStaleSessions, 300000);

app.post('/api/session', (req, res) => {
  const { keys } = req.body as { keys: Record<string, string> };
  if (!keys || typeof keys !== 'object') {
    res.status(400).json({ error: 'Missing keys' });
    return;
  }
  const sessionId = createSession(keys);
  res.json({ sessionId });
});

app.delete('/api/session/:id', (req, res) => {
  deleteSession(req.params.id);
  res.json({ ok: true });
});

app.get('/api/stream', async (req, res) => {
  const sessionId = req.query.sessionId as string;
  const session = sessionId ? getSession(sessionId) : undefined;

  const keys = session?.keys ?? {};

  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
  });

  const send = (nodeId: string, status: string, message: string) => {
    res.write(`data: ${JSON.stringify({ nodeId, status, message, timestamp: Date.now() })}\n\n`);
  };

  send('__system__', 'running', '[SSE] Stream established');

  const delay = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

  try {
    send('input-1', 'running', '[SSE] 需求接收中...');
    await delay(1500);
    send('input-1', 'done', '[SSE] 需求已接收');

    send('task-arch', 'running', '[SSE] 架构拆解启动...');
    await delay(2500);
    send('task-arch', 'done', '[SSE] 拆解完成：逻辑层 + UI层');

    const codexKey = keys.codex || '';
    const traeKey = keys.trae || '';
    const claudeKey = keys.claude || '';

    send('agent-codex', 'running', '[SSE] Codex 启动代码生成...');

    const codexPromise = (async () => {
      if (codexKey) {
        await streamCodex(
          'Generate a React component: a simple counter with increment and decrement buttons using TypeScript and Tailwind CSS.',
          codexKey,
          (chunk) => send('agent-codex', 'running', `[Codex] ${chunk}`),
        );
      } else {
        await delay(3000);
        send('agent-codex', 'running', '[Codex] (模拟) 生成 Counter 组件...');
        await delay(2000);
      }
      send('agent-codex', 'done', '[SSE] Codex 代码生成完成 ✓');
    })();

    send('agent-trae', 'running', '[SSE] Trae Solo 启动 UI 生成...');

    const traePromise = (async () => {
      const uiCode = traeKey
        ? `// Generated by Trae Solo\nexport function GeneratedUI() {\n  return <div className="p-4 text-neutral-200">Trae UI Output</div>;\n}\n`
        : `// Simulated Trae output\nexport function GeneratedUI() {\n  return <div className="p-4 text-neutral-200">Simulated UI</div>;\n}\n`;

      await delay(1500);
      const filePath = writeGeneratedFile('GeneratedUI.tsx', uiCode);
      send('agent-trae', 'running', `[Trae] Written: ${filePath}`);

      const result = await tryOpenEditor(process.cwd());
      if (result.launched) {
        send('agent-trae', 'running', `[Trae] Editor launched: ${result.editor}`);
      } else {
        send('agent-trae', 'running', '[Trae] No editor found, file saved to disk');
      }

      await delay(1500);
      send('agent-trae', 'done', '[SSE] Trae Solo UI 生成完成 ✓');
    })();

    await Promise.all([codexPromise, traePromise]);

    send('task-merge', 'running', '[SSE] 代码合并中...');
    await delay(2000);
    send('task-merge', 'done', '[SSE] 代码合并完成，0 冲突');

    send('agent-claude', 'running', '[SSE] Claude Code 开始审查...');
    if (claudeKey) {
      try {
        await spawnClaude(
          'Review the following code for bugs and suggest improvements. Be concise.',
          claudeKey,
          (chunk) => send('agent-claude', 'running', `[Claude] ${chunk}`),
        );
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        send('agent-claude', 'running', `[Claude] Spawn failed: ${msg}`);
      }
    } else {
      await delay(2000);
      send('agent-claude', 'running', '[Claude] (模拟) 审查代码中...');
      await delay(1500);
    }
    send('agent-claude', 'done', '[SSE] Claude Code 审查通过 ✓');

    send('task-done', 'running', '[SSE] 交付物打包中...');
    await delay(1000);
    send('task-done', 'done', '[SSE] 🎯 全流程完成，交付物就绪');

    send('__system__', 'done', '[SSE] Stream complete');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    send('__system__', 'error', `[SSE] Error: ${msg}`);
  } finally {
    res.end();
  }
});

app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', uptime: process.uptime() });
});

process.on('SIGINT', () => {
  killAllClaudeProcesses();
  cleanupGeneratedFiles();
  process.exit(0);
});

process.on('SIGTERM', () => {
  killAllClaudeProcesses();
  cleanupGeneratedFiles();
  process.exit(0);
});

app.listen(PORT, () => {
  console.log(`[Bridge Server] Running on http://localhost:${PORT}`);
  console.log(`[Bridge Server] SSE endpoint: http://localhost:${PORT}/api/stream`);
  console.log(`[Bridge Server] Session endpoint: POST http://localhost:${PORT}/api/session`);
});
